# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(740, 555)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../桌面/WineCup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_19 = QtWidgets.QLabel(self.centralWidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.currentTime = QtWidgets.QLineEdit(self.centralWidget)
        self.currentTime.setObjectName("currentTime")
        self.horizontalLayout_9.addWidget(self.currentTime)
        self.label_18 = QtWidgets.QLabel(self.centralWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.currentDate = QtWidgets.QLineEdit(self.centralWidget)
        self.currentDate.setObjectName("currentDate")
        self.horizontalLayout_9.addWidget(self.currentDate)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.E0 = QtWidgets.QPushButton(self.centralWidget)
        self.E0.setDefault(False)
        self.E0.setObjectName("E0")
        self.horizontalLayout_6.addWidget(self.E0)
        self.E1 = QtWidgets.QPushButton(self.centralWidget)
        self.E1.setObjectName("E1")
        self.horizontalLayout_6.addWidget(self.E1)
        self.E2 = QtWidgets.QPushButton(self.centralWidget)
        self.E2.setObjectName("E2")
        self.horizontalLayout_6.addWidget(self.E2)
        self.E3 = QtWidgets.QPushButton(self.centralWidget)
        self.E3.setObjectName("E3")
        self.horizontalLayout_6.addWidget(self.E3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.E4 = QtWidgets.QPushButton(self.centralWidget)
        self.E4.setObjectName("E4")
        self.horizontalLayout_5.addWidget(self.E4)
        self.E5 = QtWidgets.QPushButton(self.centralWidget)
        self.E5.setObjectName("E5")
        self.horizontalLayout_5.addWidget(self.E5)
        self.E6 = QtWidgets.QPushButton(self.centralWidget)
        self.E6.setObjectName("E6")
        self.horizontalLayout_5.addWidget(self.E6)
        self.E7 = QtWidgets.QPushButton(self.centralWidget)
        self.E7.setObjectName("E7")
        self.horizontalLayout_5.addWidget(self.E7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.E8 = QtWidgets.QPushButton(self.centralWidget)
        self.E8.setObjectName("E8")
        self.horizontalLayout.addWidget(self.E8)
        self.E9 = QtWidgets.QPushButton(self.centralWidget)
        self.E9.setEnabled(False)
        self.E9.setObjectName("E9")
        self.horizontalLayout.addWidget(self.E9)
        self.EA = QtWidgets.QPushButton(self.centralWidget)
        self.EA.setEnabled(False)
        self.EA.setObjectName("EA")
        self.horizontalLayout.addWidget(self.EA)
        self.EB = QtWidgets.QPushButton(self.centralWidget)
        self.EB.setEnabled(False)
        self.EB.setObjectName("EB")
        self.horizontalLayout.addWidget(self.EB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.EC = QtWidgets.QPushButton(self.centralWidget)
        self.EC.setEnabled(False)
        self.EC.setObjectName("EC")
        self.horizontalLayout_4.addWidget(self.EC)
        self.ED = QtWidgets.QPushButton(self.centralWidget)
        self.ED.setEnabled(False)
        self.ED.setObjectName("ED")
        self.horizontalLayout_4.addWidget(self.ED)
        self.EE = QtWidgets.QPushButton(self.centralWidget)
        self.EE.setEnabled(False)
        self.EE.setObjectName("EE")
        self.horizontalLayout_4.addWidget(self.EE)
        self.EF = QtWidgets.QPushButton(self.centralWidget)
        self.EF.setEnabled(False)
        self.EF.setObjectName("EF")
        self.horizontalLayout_4.addWidget(self.EF)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.F0 = QtWidgets.QPushButton(self.centralWidget)
        self.F0.setEnabled(False)
        self.F0.setObjectName("F0")
        self.horizontalLayout_2.addWidget(self.F0)
        self.F1 = QtWidgets.QPushButton(self.centralWidget)
        self.F1.setEnabled(False)
        self.F1.setObjectName("F1")
        self.horizontalLayout_2.addWidget(self.F1)
        self.F2 = QtWidgets.QPushButton(self.centralWidget)
        self.F2.setEnabled(False)
        self.F2.setObjectName("F2")
        self.horizontalLayout_2.addWidget(self.F2)
        self.F3 = QtWidgets.QPushButton(self.centralWidget)
        self.F3.setEnabled(False)
        self.F3.setObjectName("F3")
        self.horizontalLayout_2.addWidget(self.F3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.F4 = QtWidgets.QPushButton(self.centralWidget)
        self.F4.setEnabled(False)
        self.F4.setObjectName("F4")
        self.horizontalLayout_3.addWidget(self.F4)
        self.F5 = QtWidgets.QPushButton(self.centralWidget)
        self.F5.setEnabled(False)
        self.F5.setObjectName("F5")
        self.horizontalLayout_3.addWidget(self.F5)
        self.F6 = QtWidgets.QPushButton(self.centralWidget)
        self.F6.setEnabled(False)
        self.F6.setObjectName("F6")
        self.horizontalLayout_3.addWidget(self.F6)
        self.F7 = QtWidgets.QPushButton(self.centralWidget)
        self.F7.setEnabled(False)
        self.F7.setObjectName("F7")
        self.horizontalLayout_3.addWidget(self.F7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.FC = QtWidgets.QPushButton(self.centralWidget)
        self.FC.setEnabled(False)
        self.FC.setObjectName("FC")
        self.horizontalLayout_8.addWidget(self.FC)
        self.FD = QtWidgets.QPushButton(self.centralWidget)
        self.FD.setEnabled(False)
        self.FD.setObjectName("FD")
        self.horizontalLayout_8.addWidget(self.FD)
        self.FE = QtWidgets.QPushButton(self.centralWidget)
        self.FE.setEnabled(False)
        self.FE.setObjectName("FE")
        self.horizontalLayout_8.addWidget(self.FE)
        self.FF = QtWidgets.QPushButton(self.centralWidget)
        self.FF.setEnabled(False)
        self.FF.setObjectName("FF")
        self.horizontalLayout_8.addWidget(self.FF)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.F8 = QtWidgets.QPushButton(self.centralWidget)
        self.F8.setEnabled(False)
        self.F8.setObjectName("F8")
        self.horizontalLayout_7.addWidget(self.F8)
        self.F9 = QtWidgets.QPushButton(self.centralWidget)
        self.F9.setEnabled(False)
        self.F9.setObjectName("F9")
        self.horizontalLayout_7.addWidget(self.F9)
        self.FA = QtWidgets.QPushButton(self.centralWidget)
        self.FA.setEnabled(False)
        self.FA.setObjectName("FA")
        self.horizontalLayout_7.addWidget(self.FA)
        self.FB = QtWidgets.QPushButton(self.centralWidget)
        self.FB.setEnabled(False)
        self.FB.setObjectName("FB")
        self.horizontalLayout_7.addWidget(self.FB)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.currentVolume = QtWidgets.QLineEdit(self.centralWidget)
        self.currentVolume.setObjectName("currentVolume")
        self.horizontalLayout_11.addWidget(self.currentVolume)
        self.label_24 = QtWidgets.QLabel(self.centralWidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.currentAverageSpeed = QtWidgets.QLineEdit(self.centralWidget)
        self.currentAverageSpeed.setObjectName("currentAverageSpeed")
        self.horizontalLayout_11.addWidget(self.currentAverageSpeed)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.centralWidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.currentNegPressure = QtWidgets.QLineEdit(self.centralWidget)
        self.currentNegPressure.setObjectName("currentNegPressure")
        self.horizontalLayout_12.addWidget(self.currentNegPressure)
        self.label_16 = QtWidgets.QLabel(self.centralWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.currentAtmPressure = QtWidgets.QLineEdit(self.centralWidget)
        self.currentAtmPressure.setObjectName("currentAtmPressure")
        self.horizontalLayout_12.addWidget(self.currentAtmPressure)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setSpacing(6)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.UA = QtWidgets.QLineEdit(self.centralWidget)
        self.UA.setObjectName("UA")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.UA)
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.IA = QtWidgets.QLineEdit(self.centralWidget)
        self.IA.setObjectName("IA")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IA)
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.PA = QtWidgets.QLineEdit(self.centralWidget)
        self.PA.setObjectName("PA")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PA)
        self.horizontalLayout_10.addLayout(self.formLayout_6)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setSpacing(6)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.UB = QtWidgets.QLineEdit(self.centralWidget)
        self.UB.setObjectName("UB")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.UB)
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.IB = QtWidgets.QLineEdit(self.centralWidget)
        self.IB.setObjectName("IB")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IB)
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.PB = QtWidgets.QLineEdit(self.centralWidget)
        self.PB.setObjectName("PB")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PB)
        self.horizontalLayout_10.addLayout(self.formLayout_7)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setSpacing(6)
        self.formLayout_8.setObjectName("formLayout_8")
        self.UC = QtWidgets.QLineEdit(self.centralWidget)
        self.UC.setObjectName("UC")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.UC)
        self.label_20 = QtWidgets.QLabel(self.centralWidget)
        self.label_20.setObjectName("label_20")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.IC = QtWidgets.QLineEdit(self.centralWidget)
        self.IC.setObjectName("IC")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IC)
        self.label_21 = QtWidgets.QLabel(self.centralWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.PC = QtWidgets.QLineEdit(self.centralWidget)
        self.PC.setObjectName("PC")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PC)
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_10.addLayout(self.formLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.static_parameters = QtWidgets.QPushButton(self.centralWidget)
        self.static_parameters.setObjectName("static_parameters")
        self.verticalLayout_3.addWidget(self.static_parameters)
        self.saveStatueButton = QtWidgets.QPushButton(self.centralWidget)
        self.saveStatueButton.setObjectName("saveStatueButton")
        self.verticalLayout_3.addWidget(self.saveStatueButton)
        self.startBtton = QtWidgets.QPushButton(self.centralWidget)
        self.startBtton.setObjectName("startBtton")
        self.verticalLayout_3.addWidget(self.startBtton)
        self.flushButton = QtWidgets.QPushButton(self.centralWidget)
        self.flushButton.setObjectName("flushButton")
        self.verticalLayout_3.addWidget(self.flushButton)
        self.tables = QtWidgets.QPushButton(self.centralWidget)
        self.tables.setObjectName("tables")
        self.verticalLayout_3.addWidget(self.tables)
        self.saveDataButton = QtWidgets.QPushButton(self.centralWidget)
        self.saveDataButton.setObjectName("saveDataButton")
        self.verticalLayout_3.addWidget(self.saveDataButton)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_4.setSpacing(6)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_22 = QtWidgets.QLabel(self.centralWidget)
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.settingElectric = QtWidgets.QLineEdit(self.centralWidget)
        self.settingElectric.setObjectName("settingElectric")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.settingElectric)
        self.label_23 = QtWidgets.QLabel(self.centralWidget)
        self.label_23.setObjectName("label_23")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.settingVoltage = QtWidgets.QLineEdit(self.centralWidget)
        self.settingVoltage.setObjectName("settingVoltage")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.settingVoltage)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.settingSpeed = QtWidgets.QLineEdit(self.centralWidget)
        self.settingSpeed.setObjectName("settingSpeed")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.settingSpeed)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.settingTestArea = QtWidgets.QLineEdit(self.centralWidget)
        self.settingTestArea.setObjectName("settingTestArea")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.settingTestArea)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.settingPort = QtWidgets.QComboBox(self.centralWidget)
        self.settingPort.setObjectName("settingPort")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.settingPort)
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.settingCups = QtWidgets.QComboBox(self.centralWidget)
        self.settingCups.setObjectName("settingCups")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.settingCups.addItem("")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.settingCups)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label)
        self.settingBaudBox = QtWidgets.QComboBox(self.centralWidget)
        self.settingBaudBox.setObjectName("settingBaudBox")
        self.settingBaudBox.addItem("")
        self.settingBaudBox.addItem("")
        self.settingBaudBox.addItem("")
        self.settingBaudBox.addItem("")
        self.settingBaudBox.addItem("")
        self.settingBaudBox.addItem("")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.settingBaudBox)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.settingPoll = QtWidgets.QComboBox(self.centralWidget)
        self.settingPoll.setObjectName("settingPoll")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.settingPoll.addItem("")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.settingPoll)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 4, 2, 1)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setSpacing(6)
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_51 = QtWidgets.QLabel(self.centralWidget)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_61.addWidget(self.label_51)
        self.C1 = QtWidgets.QLineEdit(self.centralWidget)
        self.C1.setObjectName("C1")
        self.horizontalLayout_61.addWidget(self.C1)
        self.label_52 = QtWidgets.QLabel(self.centralWidget)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_61.addWidget(self.label_52)
        self.C2 = QtWidgets.QLineEdit(self.centralWidget)
        self.C2.setObjectName("C2")
        self.horizontalLayout_61.addWidget(self.C2)
        self.label_55 = QtWidgets.QLabel(self.centralWidget)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_61.addWidget(self.label_55)
        self.C3 = QtWidgets.QLineEdit(self.centralWidget)
        self.C3.setObjectName("C3")
        self.horizontalLayout_61.addWidget(self.C3)
        self.label_56 = QtWidgets.QLabel(self.centralWidget)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_61.addWidget(self.label_56)
        self.C4 = QtWidgets.QLineEdit(self.centralWidget)
        self.C4.setObjectName("C4")
        self.horizontalLayout_61.addWidget(self.C4)
        self.gridLayout.addLayout(self.horizontalLayout_61, 0, 0, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 2, 2, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 740, 23))
        self.menuBar.setObjectName("menuBar")
        self.menusettings = QtWidgets.QMenu(self.menuBar)
        self.menusettings.setObjectName("menusettings")
        self.menuabout = QtWidgets.QMenu(self.menuBar)
        self.menuabout.setObjectName("menuabout")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menusettings.menuAction())
        self.menuBar.addAction(self.menuabout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智能风机性能测试系统"))
        self.label_19.setText(_translate("MainWindow", "当前时间："))
        self.label_18.setText(_translate("MainWindow", " 当前日期:"))
        self.E0.setText(_translate("MainWindow", "表1："))
        self.E1.setText(_translate("MainWindow", "表2："))
        self.E2.setText(_translate("MainWindow", "表3："))
        self.E3.setText(_translate("MainWindow", "表4："))
        self.E4.setText(_translate("MainWindow", "表5："))
        self.E5.setText(_translate("MainWindow", "表6："))
        self.E6.setText(_translate("MainWindow", "表7："))
        self.E7.setText(_translate("MainWindow", "表8："))
        self.E8.setText(_translate("MainWindow", "表9："))
        self.E9.setText(_translate("MainWindow", "表10："))
        self.EA.setText(_translate("MainWindow", "表11："))
        self.EB.setText(_translate("MainWindow", "表12："))
        self.EC.setText(_translate("MainWindow", "表13："))
        self.ED.setText(_translate("MainWindow", "表14："))
        self.EE.setText(_translate("MainWindow", "表15："))
        self.EF.setText(_translate("MainWindow", "表16："))
        self.F0.setText(_translate("MainWindow", "表17："))
        self.F1.setText(_translate("MainWindow", "表18："))
        self.F2.setText(_translate("MainWindow", "表19："))
        self.F3.setText(_translate("MainWindow", "表20："))
        self.F4.setText(_translate("MainWindow", "表21："))
        self.F5.setText(_translate("MainWindow", "表22："))
        self.F6.setText(_translate("MainWindow", "表23："))
        self.F7.setText(_translate("MainWindow", "表24："))
        self.FC.setText(_translate("MainWindow", "表29："))
        self.FD.setText(_translate("MainWindow", "表30："))
        self.FE.setText(_translate("MainWindow", "表31："))
        self.FF.setText(_translate("MainWindow", "表32："))
        self.F8.setText(_translate("MainWindow", "表25："))
        self.F9.setText(_translate("MainWindow", "表26："))
        self.FA.setText(_translate("MainWindow", "表27："))
        self.FB.setText(_translate("MainWindow", "表28："))
        self.label_13.setText(_translate("MainWindow", "当前风量:"))
        self.label_24.setText(_translate("MainWindow", "平均风速:"))
        self.label_17.setText(_translate("MainWindow", "负压:"))
        self.label_16.setText(_translate("MainWindow", "大气压:"))
        self.label_5.setText(_translate("MainWindow", "Ua:"))
        self.label_9.setText(_translate("MainWindow", "Ia:"))
        self.label_11.setText(_translate("MainWindow", "P:"))
        self.label_8.setText(_translate("MainWindow", "Ub:"))
        self.label_10.setText(_translate("MainWindow", "Ib:"))
        self.label_12.setText(_translate("MainWindow", "Q:"))
        self.label_20.setText(_translate("MainWindow", "Ic:"))
        self.label_21.setText(_translate("MainWindow", "cosφ:"))
        self.label_14.setText(_translate("MainWindow", "Uc:"))
        self.static_parameters.setText(_translate("MainWindow", "设置静态参数"))
        self.saveStatueButton.setText(_translate("MainWindow", "保存"))
        self.startBtton.setText(_translate("MainWindow", "开始"))
        self.flushButton.setText(_translate("MainWindow", "刷新"))
        self.tables.setText(_translate("MainWindow", "图表"))
        self.saveDataButton.setText(_translate("MainWindow", "历史数据"))
        self.label_22.setText(_translate("MainWindow", "电压变比:"))
        self.label_23.setText(_translate("MainWindow", "电流变比:"))
        self.label_3.setText(_translate("MainWindow", "风杯速度:"))
        self.label_4.setText(_translate("MainWindow", "测断面面积:"))
        self.label_7.setText(_translate("MainWindow", "端口号:"))
        self.label_6.setText(_translate("MainWindow", "风杯数:"))
        self.settingCups.setItemText(0, _translate("MainWindow", "9个"))
        self.settingCups.setItemText(1, _translate("MainWindow", "1个"))
        self.settingCups.setItemText(2, _translate("MainWindow", "2个"))
        self.settingCups.setItemText(3, _translate("MainWindow", "3个"))
        self.settingCups.setItemText(4, _translate("MainWindow", "4个"))
        self.settingCups.setItemText(5, _translate("MainWindow", "5个"))
        self.settingCups.setItemText(6, _translate("MainWindow", "6个"))
        self.settingCups.setItemText(7, _translate("MainWindow", "7个"))
        self.settingCups.setItemText(8, _translate("MainWindow", "8个"))
        self.settingCups.setItemText(9, _translate("MainWindow", "10个"))
        self.settingCups.setItemText(10, _translate("MainWindow", "11个"))
        self.settingCups.setItemText(11, _translate("MainWindow", "12个"))
        self.settingCups.setItemText(12, _translate("MainWindow", "13个"))
        self.settingCups.setItemText(13, _translate("MainWindow", "14个"))
        self.settingCups.setItemText(14, _translate("MainWindow", "15个"))
        self.settingCups.setItemText(15, _translate("MainWindow", "16个"))
        self.settingCups.setItemText(16, _translate("MainWindow", "17个"))
        self.settingCups.setItemText(17, _translate("MainWindow", "18个"))
        self.settingCups.setItemText(18, _translate("MainWindow", "19个"))
        self.settingCups.setItemText(19, _translate("MainWindow", "20个"))
        self.settingCups.setItemText(20, _translate("MainWindow", "21个"))
        self.settingCups.setItemText(21, _translate("MainWindow", "22个"))
        self.settingCups.setItemText(22, _translate("MainWindow", "23个"))
        self.settingCups.setItemText(23, _translate("MainWindow", "24个"))
        self.settingCups.setItemText(24, _translate("MainWindow", "25个"))
        self.settingCups.setItemText(25, _translate("MainWindow", "26个"))
        self.settingCups.setItemText(26, _translate("MainWindow", "27个"))
        self.settingCups.setItemText(27, _translate("MainWindow", "28个"))
        self.settingCups.setItemText(28, _translate("MainWindow", "29个"))
        self.settingCups.setItemText(29, _translate("MainWindow", "30个"))
        self.settingCups.setItemText(30, _translate("MainWindow", "31个"))
        self.settingCups.setItemText(31, _translate("MainWindow", "32个"))
        self.label.setText(_translate("MainWindow", "波特率:"))
        self.settingBaudBox.setItemText(0, _translate("MainWindow", "9600"))
        self.settingBaudBox.setItemText(1, _translate("MainWindow", "1200"))
        self.settingBaudBox.setItemText(2, _translate("MainWindow", "2400"))
        self.settingBaudBox.setItemText(3, _translate("MainWindow", "4800"))
        self.settingBaudBox.setItemText(4, _translate("MainWindow", "19200"))
        self.settingBaudBox.setItemText(5, _translate("MainWindow", "38400"))
        self.label_2.setText(_translate("MainWindow", "轮询间隔: "))
        self.settingPoll.setItemText(0, _translate("MainWindow", "50ms"))
        self.settingPoll.setItemText(1, _translate("MainWindow", "60ms"))
        self.settingPoll.setItemText(2, _translate("MainWindow", "70ms"))
        self.settingPoll.setItemText(3, _translate("MainWindow", "80ms"))
        self.settingPoll.setItemText(4, _translate("MainWindow", "90ms"))
        self.settingPoll.setItemText(5, _translate("MainWindow", "100ms"))
        self.settingPoll.setItemText(6, _translate("MainWindow", "150ms"))
        self.settingPoll.setItemText(7, _translate("MainWindow", "200ms"))
        self.settingPoll.setItemText(8, _translate("MainWindow", "250ms"))
        self.settingPoll.setItemText(9, _translate("MainWindow", "300ms"))
        self.settingPoll.setItemText(10, _translate("MainWindow", "350ms"))
        self.settingPoll.setItemText(11, _translate("MainWindow", "400ms"))
        self.settingPoll.setItemText(12, _translate("MainWindow", "450ms"))
        self.settingPoll.setItemText(13, _translate("MainWindow", "500ms"))
        self.settingPoll.setItemText(14, _translate("MainWindow", "1000ms"))
        self.settingPoll.setItemText(15, _translate("MainWindow", "2000ms"))
        self.settingPoll.setItemText(16, _translate("MainWindow", "4000ms"))
        self.label_51.setText(_translate("MainWindow", "受检单位："))
        self.label_52.setText(_translate("MainWindow", "委托单位："))
        self.label_55.setText(_translate("MainWindow", "风机型号："))
        self.label_56.setText(_translate("MainWindow", "风叶角度："))
        self.menusettings.setTitle(_translate("MainWindow", "设置"))
        self.menuabout.setTitle(_translate("MainWindow", "关于"))

